export const LOCATIONS = {
  borivali: {
    name: 'Borivali West',
    slug: 'borivali',
    address: 'Shop 13, Ground Floor, Nutan Dreams, Babhai Naka, Near Govind Nagar, Vasant Chougale Road, Borivali West, Mumbai 400092',
    phone: '8169817022',
    email: 'care@cocobroma.com',
    whatsapp: 'https://wa.me/918169817022',
    hours: '10:00 AM – 11:00 PM, Every Day',
    mapEmbedUrl: 'https://maps.google.com/maps?q=CocoBroma+Borivali&output=embed',
    mapsLink: 'https://maps.google.com/?q=CocoBroma+Borivali+West',
    zomatoUrl: 'https://www.zomato.com/mumbai/cocobroma-borivali',
    swiggyUrl: 'https://www.swiggy.com/',
    landmarks: ['Near Babhai Naka', 'Vasant Chougale Road', 'Near Govind Nagar'],
  },
  andheri: {
    name: 'Andheri West',
    slug: 'andheri',
    address: 'Shop 12, Sundervan Complex, Shastri Nagar, Andheri Lokhandwala, Andheri West, Mumbai 400053',
    phone: '8169817022',
    email: 'care@cocobroma.com',
    whatsapp: 'https://wa.me/918169817022',
    hours: '10:00 AM – 11:00 PM, Every Day',
    mapEmbedUrl: 'https://maps.google.com/maps?q=CocoBroma+Andheri&output=embed',
    mapsLink: 'https://maps.google.com/?q=CocoBroma+Andheri+West+Lokhandwala',
    zomatoUrl: 'https://www.zomato.com/mumbai/cocobroma-andheri',
    swiggyUrl: 'https://www.swiggy.com/',
    landmarks: ['Sundervan Complex', 'Lokhandwala', 'Shastri Nagar'],
  },
  kandivali: {
    name: 'Kandivali',
    slug: 'kandivali',
    address: 'Kandivali, Mumbai',
    phone: '8169817022',
    email: 'care@cocobroma.com',
    whatsapp: 'https://wa.me/918169817022',
    hours: '10:00 AM – 11:00 PM, Every Day',
    mapEmbedUrl: '',  // fill after confirming address
    mapsLink: '',
    zomatoUrl: '',
    swiggyUrl: '',
    landmarks: [],
  },
} as const;
